# Generated by Django 5.1.5 on 2025-01-22 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointment", "0001_initial"),
        ("doctors", "0002_doctorreg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="doctor_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors.doctorreg",
            ),
        ),
    ]
