# Generated by Django 5.1.5 on 2025-01-23 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0006_doctorreg"),
        ("Appointment", "0002_alter_appointment_doctor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="doctor_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Accounts.doctorreg",
            ),
        ),
    ]
