# Generated by Django 5.1.5 on 2025-01-22 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctorreg",
            name="member",
        ),
        migrations.RemoveField(
            model_name="doctorreg",
            name="other_specializations_id",
        ),
    ]
