# Generated by Django 5.1.5 on 2025-01-22 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Appointment", "0002_alter_appointment_doctor_id"),
        ("Dashboard", "0002_remove_doctorreg_member_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DoctorReg",
        ),
    ]
