# Generated by Django 5.1.4 on 2025-01-08 18:49

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member_code',
            field=models.CharField(default=Accounts.models.generate_service_id, max_length=6, null=True),
        ),
    ]
