# Generated by Django 5.1.4 on 2025-01-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ID',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Patient ID', 'verbose_name_plural': 'Patient IDs'},
        ),
        migrations.AddField(
            model_name='nextofkin',
            name='registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
