# Generated by Django 5.1.5 on 2025-01-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0002_delete_id_alter_user_options_nextofkin_registered_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
