# Generated by Django 5.1.4 on 2025-01-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_user_member_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='/icon/bondijunction_dentalclinic_logo-300x258.jpg', null=True, upload_to='profile_photos/'),
        ),
    ]
