# Generated by Django 5.1.5 on 2025-01-22 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0003_alter_user_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_Doctor",
            new_name="registration_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_Member_Patient",
        ),
        migrations.RemoveField(
            model_name="user",
            name="registered",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("doctor", "Doctor"), ("patient", "Patient")],
                default="patient",
                error_messages={"required": "Role must be provided"},
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default="defaults/user.png", upload_to="profile_photos/"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("about", models.TextField(blank=True, null=True)),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "price_per_consultation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("allergies", models.TextField(blank=True, null=True)),
                ("medical_conditions", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
