# Generated by Django 5.1.5 on 2025-01-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0004_rename_is_doctor_user_registration_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="patient_type",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("doctor", "Doctor"),
                    ("patient", "Patient"),
                    ("Staff", "Staff"),
                ],
                default="patient",
                error_messages={"required": "Role must be provided"},
                max_length=20,
            ),
        ),
    ]
