# Generated by Django 5.1.4 on 2025-01-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='icon/bondijunction_dentalclinic_logo-300x258.jpg', upload_to='profile_photos/'),
        ),
    ]
