# Generated by Django 5.1.4 on 2025-01-09 11:24

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member_code',
            field=models.CharField(default=Accounts.models.generate_service_id, max_length=6, unique=True),
        ),
    ]
