# Generated by Django 5.1.5 on 2025-01-23 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0006_doctorreg"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctorreg",
            old_name="member",
            new_name="doctor",
        ),
        migrations.RemoveField(
            model_name="doctorreg",
            name="mobile_number",
        ),
    ]
