# Generated by Django 5.1.4 on 2025-01-11 14:38

import Clinic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagetitle', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('aboutus', models.TextField()),
                ('email', models.EmailField(max_length=200)),
                ('mobilenumber', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(default=Clinic.models.generate_service_id, max_length=6, null=True)),
                ('sname', models.CharField(max_length=100, null=True)),
                ('service_title', models.CharField(max_length=225, null=True)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='services_image/')),
                ('service_logo', models.ImageField(blank=True, null=True, upload_to='service_logo/')),
                ('service_price', models.IntegerField(null=True)),
                ('ratings', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
