# Generated by Django 5.1.5 on 2025-01-15 15:59

import Clinic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Clinic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blog_code",
                    models.CharField(
                        default=Clinic.models.generate_service_id,
                        max_length=6,
                        null=True,
                    ),
                ),
                ("blog_title", models.CharField(max_length=250)),
                ("blog_subtitle", models.CharField(max_length=250)),
                (
                    "blog_image",
                    models.ImageField(
                        default="icon/bondijunction_dentalclinic_logo-300x258.jpg",
                        upload_to="profile_photos/",
                    ),
                ),
                ("blog_member", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
