# Generated by Django 5.1.4 on 2025-01-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
    ]
