# Generated by Django 5.1.5 on 2025-01-22 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("doctors", "0002_doctorreg"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="doctor",
            field=models.ForeignKey(
                limit_choices_to={"specializations": "1"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="doctors.doctorreg",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="patient",
            field=models.ForeignKey(
                limit_choices_to={"specialization": "patient"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
