# Generated by Django 5.1.5 on 2025-01-22 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_doctor_alter_booking_patient"),
        ("doctors", "0002_doctorreg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="doctors.doctorreg",
            ),
        ),
    ]
