# Generated by Django 5.1.5 on 2025-01-22 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointment", "0002_alter_appointment_doctor_id"),
        ("bookings", "0004_alter_booking_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="patient",
            field=models.ForeignKey(
                limit_choices_to={"email": "email"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_appointments",
                to="Appointment.appointment",
            ),
        ),
    ]
