# Generated by Django 5.1.5 on 2025-01-22 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointment", "0002_alter_appointment_doctor_id"),
        ("bookings", "0006_alter_booking_patient"),
        ("doctors", "0002_doctorreg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions_given",
                to="doctors.doctorreg",
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions_received",
                to="Appointment.appointment",
            ),
        ),
    ]
