# Generated by Django 5.1.5 on 2025-01-23 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0006_doctorreg"),
        ("bookings", "0007_alter_prescription_doctor_alter_prescription_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="Accounts.doctorreg",
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions_given",
                to="Accounts.doctorreg",
            ),
        ),
    ]
