# Generated by Django 5.1.5 on 2025-01-23 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0007_rename_member_doctorreg_doctor_and_more"),
        ("Appointment", "0003_alter_appointment_doctor_id"),
        ("bookings", "0008_alter_booking_doctor_alter_prescription_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="doctor",
            field=models.ForeignKey(
                limit_choices_to={"role": "doctor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="Accounts.doctorreg",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="patient",
            field=models.ForeignKey(
                limit_choices_to={"role": "patient"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_appointments",
                to="Appointment.appointment",
            ),
        ),
    ]
