# Generated by Django 5.1.5 on 2025-01-23 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Appointment", "0003_alter_appointment_doctor_id"),
        ("bookings", "0008_alter_booking_doctor_alter_prescription_doctor"),
        ("doctors", "0002_doctorreg"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DoctorReg",
        ),
    ]
